// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineMarket.DataAccess.Context;

#nullable disable

namespace OnlineMarket.DataAccess.Migrations
{
    [DbContext(typeof(OnlineMarketDbContext))]
    [Migration("20230426063004_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineMarket.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 10,
                            CreatedAt = new DateTime(2023, 4, 26, 6, 30, 4, 153, DateTimeKind.Utc).AddTicks(6040),
                            Description = "A high-end smartphone with 6.7-inch Super Retina XDR display and 5G connectivity.",
                            Name = "Apple iPhone 13 Pro Max",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 2,
                            Count = 5,
                            CreatedAt = new DateTime(2023, 4, 26, 6, 30, 4, 153, DateTimeKind.Utc).AddTicks(6044),
                            Description = "A mid-range smartphone with 6.2-inch Dynamic AMOLED display and 5G connectivity.",
                            Name = "Samsung Galaxy S21",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            Count = 2,
                            CreatedAt = new DateTime(2023, 4, 26, 6, 30, 4, 153, DateTimeKind.Utc).AddTicks(6045),
                            Description = "A foldable smartphone with 6.2-inch Flex View OLED display and 5G connectivity.",
                            Name = "Motorola Razr 5G",
                            Price = 1399.99m
                        },
                        new
                        {
                            Id = 4,
                            Count = 15,
                            CreatedAt = new DateTime(2023, 4, 26, 6, 30, 4, 153, DateTimeKind.Utc).AddTicks(6046),
                            Description = "A budget smartphone with 6.5-inch IPS LCD display and 4G connectivity.",
                            Name = "Xiaomi Redmi 10",
                            Price = 179.99m
                        },
                        new
                        {
                            Id = 5,
                            Count = 7,
                            CreatedAt = new DateTime(2023, 4, 26, 6, 30, 4, 153, DateTimeKind.Utc).AddTicks(6048),
                            Description = "A high-end smartphone with 6.7-inch Fluid AMOLED display and 5G connectivity.",
                            Name = "OnePlus 9 Pro",
                            Price = 899.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
